Add missing include for ssize_t on FreeBSD.
src/tvhlog.h:48: error: expected declaration specifiers or '...' before 'ssize_t'
src/tvhlog.c:244: error: conflicting types for '_tvhlog_hexdump'
src/tvhlog.h:48: error: previous declaration of '_tvhlog_hexdump' was here