Add missing include for "struct iovec" which is defined in sys/uio.h on FreeBSD and also on Linux.
tvheadend-3.4/src/muxer/tvh/mkmux.c: In function 'mk_write_to_fd':
tvheadend-3.4/src/muxer/tvh/mkmux.c:347: error: invalid application of 'sizeof' to incomplete type 'struct iovec'
tvheadend-3.4/src/muxer/tvh/mkmux.c:351: error: invalid use of undefined type 'struct iovec'
tvheadend-3.4/src/muxer/tvh/mkmux.c:351: error: dereferencing pointer to incomplete type
tvheadend-3.4/src/muxer/tvh/mkmux.c:352: error: invalid use of undefined type 'struct iovec'
tvheadend-3.4/src/muxer/tvh/mkmux.c:352: error: dereferencing pointer to incomplete type
cc1: warnings being treated as errors
tvheadend-3.4/src/muxer/tvh/mkmux.c:358: warning: implicit declaration of function 'writev'
tvheadend-3.4/src/muxer/tvh/mkmux.c:364: error: invalid use of undefined type 'struct iovec'