build: Add missing include for Dl_info on FreeBSD which is only used when execinfo is enabled.
src/trap.c:144: error: 'Dl_info' undeclared (first use in this function)
src/trap.c:144: error: expected ';' before 'dli'
cc1: warnings being treated as errors
src/trap.c:187: warning: implicit declaration of function 'dladdr'
src/trap.c:187: error: 'dli' undeclared (first use in this function)