Add missing include for FreeBSD which has AF_INET defined in sys/socket.h
tvheadend-3.4/src/webui/comet.c: In function 'comet_serverIpPort':
tvheadend-3.4/src/webui/comet.c:162: error: 'AF_INET' undeclared (first use in this function)
tvheadend-3.4/src/webui/comet.c:162: error: (Each undeclared identifier is reported only once
tvheadend-3.4/src/webui/comet.c:162: error: for each function it appears in.)
tvheadend-3.4/src/webui/comet.c:164: error: 'AF_INET6' undeclared (first use in this function)